name: project_stable_compose
services:
  frontend:
    image: inchanterx/faberge-frontend:stable
    pull_policy: always
    ports:
      - "3000:80"
    depends_on: 
      - gateway

  gateway:
    image: inchanterx/faberge-apigateway:stable
    pull_policy: always
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - project

  auth:
    image: inchanterx/faberge-auth-service:stable
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  project:
    image: inchanterx/faberge-project-service:stable
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  feed:
    build: ../feed_service
    container_name: feed
    volumes:
      - ../feed_service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "8000"
