name: frontend_stable_compose
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on: 
      - gateway

  gateway:
    image: inchanterx/faberge-apigateway:latest
    pull_policy: always
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - project

  auth:
    image: inchanterx/faberge-auth-service:latest
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  project:
    image: inchanterx/faberge-project-service:latest
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5