name: frontend_dev_compose
services:
  frontend:
    build:
      context: ../frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules

  gateway:
    image: inchanterx/faberge-apigateway:develop
    pull_policy: always
    ports:
      - "8080:8080"
    depends_on:
      - auth
      - project

  auth:
    image: inchanterx/faberge-auth-service:develop
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  project:
    image: inchanterx/faberge-project-service:develop
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  feed:
    image: inchanterx/faberge-feed-service:develop
    pull_policy: always
    expose:
    - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
