#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_PROFILE" --dbname "$POSTGRES_DB_PROFILE" <<-EOSQL
 
    REVOKE ALL ON DATABASE "$POSTGRES_DB_PROFILE" FROM PUBLIC;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB_PROFILE" TO "$POSTGRES_USER_PROFILE";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$POSTGRES_USER_PROFILE";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_PROFILE"
        IN SCHEMA public
        GRANT ALL ON TABLES TO "$POSTGRES_USER_PROFILE";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_PROFILE"
        IN SCHEMA public
        GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_PROFILE";
 
EOSQL
 
echo "Init completed - DB: $POSTGRES_DB_PROFILE / user: $POSTGRES_USER_PROFILE"