#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_FEED" --dbname "$POSTGRES_DB_FEED" <<-EOSQL
 
    REVOKE ALL ON DATABASE "$POSTGRES_DB_FEED" FROM PUBLIC;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB_FEED" TO "$POSTGRES_USER_FEED";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$POSTGRES_USER_FEED";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_FEED"
        IN SCHEMA public
        GRANT ALL ON TABLES TO "$POSTGRES_USER_FEED";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_FEED"
        IN SCHEMA public
        GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_FEED";
 
EOSQL
 
echo "Init completed - DB: $POSTGRES_DB_FEED / user: $POSTGRES_USER_FEED"