#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_PROJECT" --dbname "$POSTGRES_DB_PROJECT" <<-EOSQL
 
    REVOKE ALL ON DATABASE "$POSTGRES_DB_PROJECT" FROM PUBLIC;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB_PROJECT" TO "$POSTGRES_USER_PROJECT";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$POSTGRES_USER_PROJECT";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_PROJECT"
        IN SCHEMA public
        GRANT ALL ON TABLES TO "$POSTGRES_USER_PROJECT";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_PROJECT"
        IN SCHEMA public
        GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_PROJECT";
 
EOSQL
 
echo "Init completed - DB: $POSTGRES_DB_PROJECT / user: $POSTGRES_USER_PROJECT"