#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_MEDIA" --dbname "$POSTGRES_DB_MEDIA" <<-EOSQL
 
    REVOKE ALL ON DATABASE "$POSTGRES_DB_MEDIA" FROM PUBLIC;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB_MEDIA" TO "$POSTGRES_USER_MEDIA";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$POSTGRES_USER_MEDIA";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_MEDIA"
        IN SCHEMA public
        GRANT ALL ON TABLES TO "$POSTGRES_USER_MEDIA";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_MEDIA"
        IN SCHEMA public
        GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_MEDIA";
 
EOSQL
 
echo "Init completed - DB: $POSTGRES_DB_MEDIA / user: $POSTGRES_USER_MEDIA"