#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_RESPONSE" --dbname "$POSTGRES_DB_RESPONSE" <<-EOSQL
 
    REVOKE ALL ON DATABASE "$POSTGRES_DB_RESPONSE" FROM PUBLIC;
    GRANT CONNECT ON DATABASE "$POSTGRES_DB_RESPONSE" TO "$POSTGRES_USER_RESPONSE";
    GRANT ALL PRIVILEGES ON SCHEMA public TO "$POSTGRES_USER_RESPONSE";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_RESPONSE"
        IN SCHEMA public
        GRANT ALL ON TABLES TO "$POSTGRES_USER_RESPONSE";
 
    ALTER DEFAULT PRIVILEGES FOR ROLE "$POSTGRES_USER_RESPONSE"
        IN SCHEMA public
        GRANT ALL ON SEQUENCES TO "$POSTGRES_USER_RESPONSE";
 
EOSQL
 
echo "Init completed - DB: $POSTGRES_DB_RESPONSE / user: $POSTGRES_USER_RESPONSE"